-- CREATE TABLE coordinators (
--   id SERIAL PRIMARY KEY,
--   name VARCHAR(255) NOT NULL,
--   email VARCHAR(255) UNIQUE NOT NULL,
--   password VARCHAR(255) NOT NULL,
--   mobile VARCHAR(15) NOT NULL,
--   category1 VARCHAR(100),
--   event1 VARCHAR(255),
--   category2 VARCHAR(100),
--   event2 VARCHAR(255),
--   role VARCHAR(50) DEFAULT 'coordinator',
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
