CREATE TABLE individual_registrations (
  id SERIAL PRIMARY KEY,
  event_id VARCHAR(100) NOT NULL,
  event_name VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  mobile VARCHAR(15) NOT NULL,
  roll_no VARCHAR(100) NOT NULL,
  year VARCHAR(10) NOT NULL,
  branch VARCHAR(100) NOT NULL,
  college VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  transaction_id VARCHAR(255) NOT NULL,
  screenshot_url VARCHAR(500),
  amount INTEGER DEFAULT 100,
  payment_status VARCHAR(50) DEFAULT 'pending',
  registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE team_registrations (
  id SERIAL PRIMARY KEY,
  event_id VARCHAR(100) NOT NULL,
  event_name VARCHAR(255) NOT NULL,
  team_name VARCHAR(255) NOT NULL,
  leader_name VARCHAR(255) NOT NULL,
  leader_email VARCHAR(255) NOT NULL,
  leader_mobile VARCHAR(15) NOT NULL,
  leader_roll_no VARCHAR(100) NOT NULL,
  leader_year VARCHAR(10) NOT NULL,
  leader_branch VARCHAR(100) NOT NULL,
  leader_college VARCHAR(255) NOT NULL,
  leader_password VARCHAR(255) NOT NULL,
  member2_name VARCHAR(255),
  member2_email VARCHAR(255),
  member2_mobile VARCHAR(15),
  member2_roll_no VARCHAR(100),
  member2_year VARCHAR(10),
  member2_branch VARCHAR(100),
  member2_college VARCHAR(255),
  member3_name VARCHAR(255),
  member3_email VARCHAR(255),
  member3_mobile VARCHAR(15),
  member3_roll_no VARCHAR(100),
  member3_year VARCHAR(10),
  member3_branch VARCHAR(100),
  member3_college VARCHAR(255),
  member4_name VARCHAR(255),
  member4_email VARCHAR(255),
  member4_mobile VARCHAR(15),
  member4_roll_no VARCHAR(100),
  member4_year VARCHAR(10),
  member4_branch VARCHAR(100),
  member4_college VARCHAR(255),
  transaction_id VARCHAR(255) NOT NULL,
  screenshot_url VARCHAR(500),
  amount INTEGER NOT NULL,
  payment_status VARCHAR(50) DEFAULT 'pending',
  registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE otps (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  otp VARCHAR(6) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
